### ISSUE TITLE
GazeRecord do not works in Chrome

### ISSUE THREAD

**Issue by LuizGustavoTrufilho** [szydej/GazeCloud#1]
Hi, I'm a computer engineer student and testing your GazeCloud solution I've got an error in my browser (Chrome v.83):"Cannot connect to the GazeCloud server!". Please, can you help me with this problem?

**Comment by szydej** [comment]
We just added support for last google chrome version 84. All works fine now.

**Comment by szydej** [comment]
We just added support for last google chrome version 84. All works fine now.
